<?php $page='compare'; include "includes/header.php";?>
      <div class="freeTrialImage d-flex md-auto">
<a href="trialRequest.php"><img src="img/freetrial.png" class="img-fluid freeTrialImg animate__animated animate__bounce" style="height: 250px;"></a>
  </div>
    <!-- content starts here -->
            <div class="container">
                <div class="row g-3">
                    <!-- first table column start -->
                    <div class="col-md-12 col-12">
                        <table class="table comparisonTable table-striped table-hover">
                            <thead>
                                <tr>
                                    <th>
                                        
                                    </th>
                                    <th>
                                        <img class="img-fluid packageComparison d-flex mx-auto" src="img/basic.png">
                                        <b><p class="text-center">BASIC</p></b>
                                    </th>
                                    <th>
                                        <img class="img-fluid packageComparison d-flex mx-auto" src="img/professional.png">
                                        <b><p class="text-center">PROFESSIONAL</p></b>
                                    </th>
                                    <th>
                                        <img class="img-fluid packageComparison d-flex mx-auto" src="img/enterprise.png">
                                        <b><p class="text-center">ENTERPRISE</p></b>
                                    </th>
                                </thead>
                                </tr>
                                <tr>
                                    <td>
                                        Employee Self-service 
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        Notifications
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        User Roles
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        User Management
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        Report Exporting
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        Personnel Information Management
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        Employee Reports
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        Payroll
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        Payslips
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        Direct Payment to Bank
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        Dashboard
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                    Audit Trail
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        Corporate Directory
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        Organizational Chart
                                    </td>
                                    <td>
                                        &#128473;
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        Asset Tracking
                                    </td>
                                    <td>
                                        &#128473;
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        Electronic Document Management
                                    </td>
                                    <td>
                                        &#128473;
                                    </td>
                                    <td>
                                        &#128473;
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        Corporate News
                                    </td>
                                    <td>
                                        &#128473;
                                    </td>
                                    <td>
                                        &#128473;
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        Unlimited Leave Types
                                    </td>
                                    <td>
                                        &#128473;
                                    </td>
                                    <td>
                                        &#128473;
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        Unlimited Leave Rules
                                    </td>
                                    <td>
                                        &#128473;
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        Country-based Public Holidays
                                    </td>
                                    <td>
                                        &#128473;
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        Custom Work Weeks
                                    </td>
                                    <td>
                                        &#128473;
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        Leave Calender
                                    </td>
                                    <td>
                                        &#128473;
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        Leave Reports
                                    </td>
                                    <td>
                                        &#128473;
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        Timesheets
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        Attendance
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        Timesheets and Attendance Reports
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        Integrated Magnetic Card-reader and Biometric Device Support
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        Create Vacancies and Publish
                                    </td>
                                    <td>
                                        &#128473;
                                    </td>
                                    <td>
                                        &#128473;
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        External Job Site Synchronization
                                    </td>
                                    <td>
                                        &#128473;
                                    </td>
                                    <td>
                                        &#128473;
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        Create Job Application Forms
                                    </td>
                                    <td>
                                        &#128473;
                                    </td>
                                    <td>
                                        &#128473;
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        Matching Criteria
                                    </td>
                                    <td>
                                        &#128473;
                                    </td>
                                    <td>
                                        &#128473;
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        Vacancy Applicants' Report
                                    </td>
                                    <td>
                                        &#128473;
                                    </td>
                                    <td>
                                        &#128473;
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        360 Employee Review
                                    </td>
                                    <td>
                                        &#128473;
                                    </td>
                                    <td>
                                        &#128473;
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        KPI & KPI Groups Management
                                    </td>
                                    <td>
                                        &#128473;
                                    </td>
                                    <td>
                                        &#128473;
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        Automatic Performance Rating Calculation
                                    </td>
                                    <td>
                                        &#128473;
                                    </td>
                                    <td>
                                        &#128473;
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        Performance Reports
                                    </td>
                                    <td>
                                        &#128473;
                                    </td>
                                    <td>
                                        &#128473;
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        Full Training Catalogue
                                    </td>
                                    <td>
                                        &#128473;
                                    </td>
                                    <td>
                                        &#128473;
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        Employee Course/Training Planner
                                    </td>
                                    <td>
                                        &#128473;
                                    </td>
                                    <td>
                                        &#128473;
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        Training Reports
                                    </td>
                                    <td>
                                        &#128473;
                                    </td>
                                    <td>
                                        &#128473;
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        Automatic Updates
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        Flexible Deployment
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        Free Technical Support
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        Free Initial Training
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        Free Forum Support
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                    <td>
                                        &#10004;
                                    </td>
                                </tr>

                            
                        </table>
                    </div>
                    <!-- first table column end -->
                    <!-- second table column starts -->
                    
                    <!-- second table column ends -->
                </div>
            </div>
    <!-- content ends here -->
           
                <?php include "includes/footer.php" ?>